name: japan_project
description: Nice Application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  get: ^4.6.1
  flutter_form_builder: ^7.1.1
  form_builder_validators: ^7.7.0
  get_storage: ^2.0.3
  get_it: ^7.2.0
  flutter_launcher_icons: ^0.9.2
  youtube_parser: ^2.0.0
  url_launcher: ^6.0.20
  webview_flutter: ^3.0.1
  http: ^0.13.4
  flutter_calendar_carousel: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/